database:
  # Database Type
  # SQLite: A local file in your plugins folder
  # MySQL: Needs an external database server. It's faster and more reliable than SQLite
  type: "SQLite"

  # Only needed if using MySQL
  # Address of the Database server
  address: "172.18.0.1"
  # Server port. Standard is 3306
  port: 3306
  # Database Username
  user: "root"
  # Database password
  password: "password"
  # Database name.
  database: "database_name"

# Select a Language from the messages.yml file
setLanguage: "en"
